name: auth0_flutter_linux
description: "Linux plugin for the Auth0 Flutter SDK."
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  auth0_flutter_platform_interface: ^1.9.0
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^2.8.0
  meta: ^1.16.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    implements: auth0_flutter
    platforms:
      linux:
        pluginClass: Auth0FlutterLinuxPlugin

