// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_content_type`, `get_static_dir`

Future<Uint8List> webAuthenticationLogin() =>
    RustLib.instance.api.crateApiFfiWebAuthenticationLogin();

Future<Uint8List> webAuthenticationLogout(
        {required String domain, required String clientId, String? returnTo}) =>
    RustLib.instance.api.crateApiFfiWebAuthenticationLogout(
        domain: domain, clientId: clientId, returnTo: returnTo);
