// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Uint8List> webAuthenticationLogin({required AuthRequestData request}) =>
    RustLib.instance.api.crateApiFfiWebAuthenticationLogin(request: request);

Future<Uint8List> webAuthenticationLogout(
        {required String domain, required String clientId, String? returnTo}) =>
    RustLib.instance.api.crateApiFfiWebAuthenticationLogout(
        domain: domain, clientId: clientId, returnTo: returnTo);

class AuthRequestData {
  final String domain;

  const AuthRequestData({
    required this.domain,
  });

  @override
  int get hashCode => domain.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthRequestData &&
          runtimeType == other.runtimeType &&
          domain == other.domain;
}
